[tender]
id = "2024DOS0550696"
description = "Technicien Support Utilisateur"
[tender.sncf]
cdc = "json/CDC_json_data.json"
#cdc = "json/CDC_no_metadata_json_data.json"
rec = "json/REC_json_data.json"
#rec = "json/REC_no_metadata_json_data.json"
[tender.responses]
cv_experiences = "json/CV_Exp_json_data.json"
#cv_experiences = "json/CV_Exp_no_metadata_json_data.json"
cv_taches = "json/CV_Taches_json_data.json"
cv_diplomes = "json/CV_Diplomes_json_data.json"
#cv_diplomes = "json/CV_Diplomes_no_metadata_json_data.json"
